export { default as Dota2 } from './Dota2.svg'
export { default as Lol } from './lol.svg'
export { default as CS2 } from './cs2.svg'
export { default as Hs } from './hs.svg'
export { default as Ow } from './ow.svg'
export { default as Pubg } from './pubg.svg'
export { default as Fortnite } from './fortnite.svg'

export { default as IconGift } from './gift.svg'
export { default as IconCirclecheck } from './circlecheck.svg'
export { default as IconCircledashed } from './circledashed.svg'
export { default as IconClock } from './clock.svg'
export { default as IconEye } from './eye.svg'
export { default as IconRefresh } from './refresh.svg'
export { default as IconScore } from './score.svg'
export { default as IconSearch } from './search.svg'
export { default as IconInfo } from './info.svg'
export { default as IconTags } from './tags.svg'